# Generated by Django 2.2 on 2019-03-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=50)),
                ('modelYear', models.IntegerField(default=2019)),
                ('mpg', models.IntegerField(default=20)),
            ],
        ),
        migrations.DeleteModel(
            name='NewCar',
        ),
    ]
